### ISSUE TITLE
Archive Headlines

### ISSUE THREAD

**Issue by robincornett** [RRWD/genesis-accessible#11]
If a user has the "Use a semantic heading structure" option checked in the plugin's settings, and has a Genesis Headline assigned to the term/CPT (and presumably author, although I have not verified) archive as well, the heading is duplicated (not duplicated, necessarily, if the Genesis headline is set to be something different than the term name or CPT label). The page output looks like this:

![image](https://cloud.githubusercontent.com/assets/4853066/5777581/f712eae4-9d61-11e4-9939-758f4d0cfdbf.png)

The Genesis Accessible headline is added below the Genesis Framework headline and description.

My initial thought is that the [GA headline](https://github.com/RRWD/genesis-accessible/blob/master/includes/headings.php#L22) function needs to be adjusted: priority needs to be changed so that it would show above the framework block if that exists, and doesn't show if a framework headline is set. This might get a little complicated if there is a framework description but no headline, as the GA headline and framework description both output an `archive-description` div.  I don't have a solution at this point but will look into it.

**Comment by GaryJones** [comment]
+1. Just been bitten with this myself.

![screenshot 2015-01-19 13 43 12](https://cloud.githubusercontent.com/assets/88371/5801275/26973262-9fe1-11e4-932e-ac61366f3735.png)

**Comment by RRWD** [comment]
@garyJ and @robincornett: can you please test this again with GA develop, G2.2 with and without Yoast SEO?

**Comment by RRWD** [comment]
In the readme.txt for 2.1 I wrote:
= Settings for Genesis version 2.1 =
- To add an H1 on archives for categories: Go to the Dashboard to Posts → Category. Edit the category and fill out the Archive Headline.
- To add an H1 on archives for tags: Go to the Dashboard to Posts → Tags. Edit the tag and fill out the Archive Headline.
So you can set the headings via the dashboard, that's why 

I agree this is a rather complex construction and I should have documented that better.
Because in Genesis 2.2 this is fixed in core, it's not relevant for G2.2, but I want to leave it as is for GA 1.2. I don;t know what I break in sites if I would change this.
I will add much ore documentation for this release and add documentation for previous releases too.

@robincornett & @GaryJones: is this ok?

**Comment by robincornett** [comment]
Isn't it only fixed in 2.2 if `genesis_a11y` is supported?

Otherwise, if the user has a newer site, and isn't on 2.2, there is still the issue of the GA plugin not outputting a heading at all, if there is no Genesis headline set. (issue #12)
