### ISSUE TITLE
Make 404 page template optional

### ISSUE THREAD

**Issue by cdils** [RRWD/genesis-accessible#13]
Currently, the plugin does not allow for a custom 404 page to be used with the theme. Consider adding a checkbox to the admin settings to make this feature optional.

**Comment by patrickodacre** [comment]
Hi RRWD/genesis-accessible,

Thank you for contacting me. I've received your email and will get back to you with a response as quickly as possible.

Cheers,

**Comment by bramd** [comment]
See PR #17

**Comment by RRWD** [comment]
@cdils @bramd @patrickodacre : In Genesis 2.2 the 404.php and sitemap.php have a filterable function genesis_sitemap( $heading ) and are default accessible (regarding to heading structure). 
So with G2.2 you can use a child theme 404 and sitemap.
In the settings of Genesis Accessible, there is a check if the version is 2.2 or higher. I that case Genesis core will be used, so your problem is fixed by default.
If you have a version < 2.2,  in the setting you can choose to use the 404 or sitemap provided with the plugin or not by setting checkboxes.
Will that solve your problems?

**Comment by RRWD** [comment]
Fixed in version 1.2
